name:                advent-of-code
version:             0.1.0.0
github:              "jeremy-miller/advent-of-code"
license:             MIT
author:              "Jeremy Miller"
maintainer:          "jgmiller88@gmail.com"
copyright:           "2019 Jeremy Miller"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeremy-miller/advent-of-code-2018#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances

dependencies:
- base >= 4.7 && < 5

executables:
  day1-part1:
    main:                Part1.hs
    source-dirs:         day1/part1
    dependencies:
      - mtl
  day1-part2:
    main:                Part2.hs
    source-dirs:         day1/part2
  day2:
    main:                Day2.hs
    source-dirs:         day2
